### ISSUE TITLE
Update peerDependency version of react router

### ISSUE THREAD

**Issue by akiran** [tcoopman/ga-react-router#1]
Today when I ran 

```
npm install 
```

I got error

```
npm ERR! peerinvalid The package react-router does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer ga-react-router@1.0.0 wants react-router@^0.11.x
```

I had react-router version 0.12.4 in my package.json

**Comment by tcoopman** [comment]
closed via https://github.com/tcoopman/ga-react-router/commit/21a09139320db2b0369577e8787c8692567a7738.

I haven't put '*' because that can also break in the future.

Published version 1.1.0
