### ISSUE TITLE
Confused about what this library actually does

### ISSUE THREAD

**Issue by callumlocke** [tcoopman/ga-react-router#13]
I'm confused about what this library is supposed to do.

Why can't I just do this (i.e. not using ga-react-router at all):

``` js
import createBrowserHistory from 'history/lib/createBrowserHistory'
const history = createBrowserHistory()

history.listen(() => {
  ga('set', 'page', window.location.pathname)
  ga('send', 'pageview')
});

React.render(<Router history={history}>{routes}</Router>, el)
```

What does ga-react-router do that the above code does not?

**Comment by tcoopman** [comment]
ga-react-router was mostly for older version of react router.
The main advantage now is that you can include ga in your builds.
