### ISSUE TITLE
Uncaught ReferenceError: GA_CONFIG is not defined

### ISSUE THREAD

**Issue by irnc** [tcoopman/ga-react-router#15]
After implementing #14, `GA_CONFIG` became required and its omission results in `Uncaught ReferenceError: GA_CONFIG is not defined` error in client environment, thus preventing tracker creation.

**Comment by maticrivo** [comment]
I created a pull request to fix this #16

**Comment by tcoopman** [comment]
released 2.1.1. Thanks!
