### ISSUE TITLE
Reduce peerDependency on react-router

### ISSUE THREAD

**Issue by mindjuice** [tcoopman/ga-react-router#4]
In the `package.json` file, the `peerDependencies` is set to include:

```
"react-router": "^0.13.x"
```

I'm currently using `ga-react-router` with `react-router` version 0.11.6, and it's working great, but it's causing npm to complain all the time about the peer dependency being invalid.

Please correct me if I'm wrong, I don't think there is anything in `ga-react-router` that actually depends on `react-router` version 0.13.x (since it's working for me).

Could you possibly reduce this `peerDependency` to at least 0.11.6 and republish?

Thanks!

**Comment by tcoopman** [comment]
Fixed in 1.3.0

**Comment by mindjuice** [comment]
Thanks Thomas!
