### ISSUE TITLE
react-router 1.0.0?

### ISSUE THREAD

**Issue by bryanlarsen** [tcoopman/ga-react-router#7]
I assume that this doesn't work with 1.0 since it has a completely different mechanism for passing state.  Or has anybody tried it with 1.0.0-beta3 or 1.0.0-beta4 yet?

**Comment by tcoopman** [comment]
I haven't looked at using this with the 1.0.0s but your guess is probably
correct that it won't work.

I should have a look at it to see what should change

**Comment by monte-hayward** [comment]
Looks like they are marching quickly toward 1.0. Yesterday v1.0.0-rc3 was released.
They've provided a very helpful upgrade guide:
https://github.com/rackt/react-router/blob/master/UPGRADE_GUIDE.md

**Comment by tcoopman** [comment]
I'm probably just going to it like this:

``` js
import ga from 'ga-react-router'
import createBrowserHistory from 'history/lib/createBrowserHistory'
const history = createBrowserHistory()

// Listen for changes to the current location. The
// listener is called once immediately.
const unlisten = history.listen(location => {
  ga.push(location);
});

React.render(<Router history={history}>{routes}</Router>, el)

// When you're finished, stop the listener.
unlisten()
```

Does anyone have objections/suggestions to this?

**Comment by nosovsh** [comment]
Another way is to listen `onUpdate` of `Router` component:

```
import createBrowserHistory from 'history/lib/createBrowserHistory'
const history = createBrowserHistory()

function onUpdate() {
  // make any analitics calls passing `window.location.pathname` to it
}

onUpdate();

React.render(<Router history={ history }  onUpdate={ onUpdate }>{ routes }</Router>, document.body);
```

**Comment by tcoopman** [comment]
updated the readme.
