### ISSUE TITLE
Uncaught TypeError: _gaReactRouter2.default.push is not a function

### ISSUE THREAD

**Issue by chrissearle** [tcoopman/ga-react-router#9]
Added the webpack config and in my js file I can "console.log(GA_TRACKING_CODE)" and see the code in the console.

Added the following:

``` javascript
import ga from 'ga-react-router'
import createBrowserHistory from 'history/lib/createBrowserHistory'

const history = createBrowserHistory()

const unlisten = history.listen(location => {
    ga.push(location);
});
```

and my router looks like:

```
    <Provider store={store}>
        <Router history={history}>{routes}</Router>
    </Provider>
```

Yet when I start I get:

Uncaught TypeError: _gaReactRouter2.default.push is not a function

So - the ga object is a _gaReactRouter2.default - and is being called in the listen block but has no push.

Any hints on what I'm doing wrong?

**Comment by chrissearle** [comment]
Hmm - debugger says that ga.default is a

``` javascript
    function analytics(state, options) {
      if (!options) {
        options = {};
      }
      options.page = state.path;
      ga('send', 'pageview', options);
    }
```

**Comment by tcoopman** [comment]
@chrissearle I've just pushed `2.0.0`. Can you check out this version. The api has changed a little bit, in that it now just exposes the google analytics api. You can check the readme.

**Comment by chrissearle** [comment]
OK - gave that a try.

package.json:
    "ga-react-router": "^2.0.0",

Initialization code is now:

``` javascript
const unlisten = history.listen(location => {
    ga.send('send', location);
});
```

And it says:

Uncaught TypeError: _gaReactRouter2.default.send is not a function

**Comment by tcoopman** [comment]
woops, that should be `ga('send', location)`. Updated the readme

**Comment by chrissearle** [comment]
Yes. That now loads the analytics.js file.

Does it work with all history types or just browserHistory? When running locally (webpack-dev-server) browserHistory doesn't work so I've been testing with hashHistory - but - while that allows the routing to work - it doesn't trigger any further network calls to google when clicking on a route URL.

Note that the line "import createBrowserHistory from 'history/lib/createBrowserHistory'" now gives me a warning to switch to "import {browserHistory} from 'react-router'" in the console. Not sure if you want to update that in the readme too?

**Comment by chrissearle** [comment]
Not to worry - got browserHistory working with historyApiFallback: true for webpack dev. Will fiddle the nginx config later.
